# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1aa814d7ebfe4e5d2abcb8a8a94026baa979868a752908ea1a799373d39ed2bb89c07e44ab52951fb18435506e2c6c56b7df87c5d7595964caf172a097353976

test:
  secret_key_base: 46a226f2dc323093fb40704bcd5946d334c2e0fc1b3d194e530947907b3ae339b2c6eba41e968df4f902afb9fa445593d166ba11b08845546cbc61c83983e719

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
